# Change these first
owner: beamable # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Beamable Auth (Basic)
    url: https://api.beamable.com/basic/auth/platform/docs
    maxResponseTime: 3000
  - name: Beamable Auth (Object)
    url: https://api.beamable.com/object/auth/platform/docs
    maxResponseTime: 3000
  - name: Beamable Accounts (Basic)
    url: https://api.beamable.com/basic/accounts/platform/docs
    maxResponseTime: 3000
  - name: Beamable Accounts (Object)
    url: https://api.beamable.com/object/accounts/platform/docs
    maxResponseTime: 3000
  - name: Beamable Inventory (Basic)
    url: https://api.beamable.com/basic/inventory/platform/docs
    maxResponseTime: 3000
  - name: Beamable Inventory (Object)
    url: https://api.beamable.com/object/inventory/platform/docs
    maxResponseTime: 3000
  - name: Beamable Stats (Basic)
    url: https://api.beamable.com/basic/stats/platform/docs
    maxResponseTime: 3000
  - name: Beamable Stats (Object)
    url: https://api.beamable.com/object/stats/platform/docs
    maxResponseTime: 3000

status-website:
  favicon: https://files.readme.io/e5eba19-small-beamable-favicon.png
  logoUrl: https://beamable.com/wp-content/uploads/2022/02/hero-isolated_logo.svg
  themeUrl: https://beamable.github.io/status/custom-theme.css

  baseUrl: /status
  name: Beamable Status
  introTitle: "Beamable API Status"
  introMessage: We are paying attention to our APIs, and we're always working on them.
  navbar:
    - title: Status
      href: /status
    - title: Docs
      href: https://docs.beamable.com/docs/beamable-overview
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
