# Change these first
owner: beamable # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Beamable Inventory (Basic)
    url: https://api.beamable.com/basic/inventory/platform/docs
    maxResponseTime: 3000

status-website:
  favicon: https://files.readme.io/e5eba19-small-beamable-favicon.png
  logoUrl: https://beamable.com/wp-content/uploads/2022/02/hero-isolated_logo.svg
  themeUrl: https://beamable.github.io/status/custom-theme.css
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  name: Beamable Status
  introTitle: "Beamable is fighting for the Game Maker."
  introMessage: This is the Beamable API status page.
  navbar:
    - title: Status
      href: /status
    - title: Docs
      href: https://docs.beamable.com/docs/beamable-overview
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
